{
 "title": "nixluon central",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "scaling governor",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(node_cpu_scaling_governor{governor=\"performance\"} * 2) + ignoring(governor) node_cpu_scaling_governor{governor=\"powersave\"}",
     "legendFormat": "cpu{{cpu}}"
    }
   ]
  },
  {
   "title": "free space",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{mountpoint=\"/\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\"}",
     "legendFormat": "total"
    }
   ]
  },
  { "title": "KPIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_replace(avg by(cpu) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])), \"cpu\", \"cpu$1\", \"cpu\", \"(.*)\") * -1 + 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "min(node_cpu_scaling_frequency_hertz)",
     "legendFormat": "min"
    },
    {
     "expr": "max(node_cpu_scaling_frequency_hertz)",
     "legendFormat": "max"
    },
    {
     "expr": "avg(node_cpu_scaling_frequency_hertz)",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "used"
    },
    {
     "expr": "node_memory_Cached_bytes + node_memory_Buffers_bytes + node_memory_KReclaimable_bytes",
     "legendFormat": "cached"
    },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "free" }
   ]
  },
  {
   "title": "IO wait",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(node_cpu_seconds_total{mode=\"iowait\"}[1m]) * 100",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg by(chip) (node_hwmon_temp_celsius) > 1",
     "legendFormat": "{{chip}}"
    },
    {
     "expr": "label_replace(max by(chip) (node_hwmon_temp_celsius), \"chip\", \"$1.max\", \"chip\", \"(.*)\") > 1",
     "legendFormat": "{{chip}}"
    },
    {
     "expr": "label_replace(min by(chip) (node_hwmon_temp_celsius), \"chip\", \"$1.min\", \"chip\", \"(.*)\") > 1",
     "legendFormat": "{{chip}}"
    },
    { "expr": "node_hwmon_fan_rpm", "legendFormat": "{{sensor}}" }
   ]
  },
  {
   "title": "free space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{mountpoint=\"/\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "batteries [Wh]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "node_power_supply_energy_watthour",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "batteries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "node_power_supply_capacity", "legendFormat": "{{power_supply}}" }
   ]
  }
 ]
}